# Generated by Django 5.1.2 on 2024-11-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
